name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          args: -vv --latest --no-exec --github-repo ${{ github.repository }}
    
  publish-source:
    name: Publish Source
    runs-on: ubuntu-latest
    needs: generate-changelog
    steps:
      - uses: actions/checkout@v4
      
      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "${{ needs.generate-changelog.outputs.release_body }}"
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
